version: '3.8'

services:
  ros_ws:
    build: ./ros_ws
    ports:
      - 10000:10000
      - 5005:5005
      - 8080:8080
    environment:
      - "ROS_MASTER_URI=http://ros_ws:11311"
      - "ROS_HOSTNAME=ros_ws"
  dds_bridge:
    build: ./dds_bridge
    ports:
      - 7414:7414/udp
      - 7415:7415/udp
    depends_on:
      - "ros_ws"
    environment:
      - "ROS_MASTER_URI=http://ros_ws:11311"
      - "ROS_HOSTNAME=dds_bridge"
  # ggs:
  #   build: ./ggs
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - "dds_bridge"
  #   env_file:
  #     - ./ggs/.env
  #   command: >
  #     /bin/bash -c "
  #       while ! nc -z dds_bridge 8881;
  #       do
  #         echo 'Waiting for DDS Bridge...';
  #         sleep 3.0;
  #       done;
  #       echo 'DDS Bridge ready!';
  #       source activate ggs && python main.py;
  #     "
  raya_dev:
    build: ./raya_dev
    depends_on:
      - "dds_bridge"
            