version: '3.8'

services:

  ros_ws:
    build: ./ros_ws
    network_mode: host


  dds_bridge:
    build: ./dds_bridge
    network_mode: host
    user: raya
    depends_on:
      - "ros_ws"
    volumes:
      - /dev/shm:/dev/shm


  ggs:
    build: 
      context: ./ggs
      dockerfile: ../override_dockerfiles/ggs.dockerfile
    network_mode: host
    user: raya
    depends_on:
      - "dds_bridge"
    env_file:
      - ./ggs/.env
    command: >
      /bin/bash -c "
        while ! nc -z localhost 8881;
        do
          echo 'Waiting for DDS Bridge...';
          sleep 3.0;
        done;
        echo 'DDS Bridge ready!';
        source activate ggs && python main.py;
      "
    environment:
      - LOG_LEVEL=DEBUG
      - VIDEO_STREAM_URL=http://ros_ws:8080/raya/cameras/stream/
    volumes:
      - /dev/shm:/dev/shm

  # raya_dev:
  #   build: ./raya_dev
  #   depends_on:
  #     - "dds_bridge"
  #   volumes:
  #   - ./raya_projects/:/root/raya_projects/
            